/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f5f7fa',
        'on-background': '#16202e',
        'on-surface': '#17222f',
        'surface-card': '#ffffff',
        'surface-subtle': '#eef2f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f8fb',
        'surface-container': '#eef2f6',
        'surface-container-high': '#dde4ec',
        'surface-container-highest': '#ced8e2',
        'surface-bright': '#ffffff',
        'surface-dim': '#dfe6ee',
        'surface-tint': '#2b4c7e',
        primary: '#2b4c7e',
        'on-primary': '#ffffff',
        'primary-container': '#e7ecf5',
        'on-primary-container': '#1e3a66',
        'primary-fixed': '#e7ecf5',
        'primary-fixed-dim': '#c9d6ea',
        'inverse-primary': '#9fc3ea',
        'accent-cyan-deep': '#1f3c64',
        secondary: '#0f6e5c',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0f0ea',
        'secondary-fixed': '#e0f0ea',
        'secondary-fixed-dim': '#bfe0d4',
        'on-secondary-container': '#0a4036',
        tertiary: '#0f7b63',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d8f2ea',
        'tertiary-fixed-dim': '#b6e6d8',
        'on-tertiary-container': '#07443a',
        'text-primary': '#17222f',
        'text-secondary': '#3e4b59',
        'text-muted': '#7d8a99',
        'on-surface-variant': '#45525f',
        outline: '#aeb9c5',
        'outline-variant': '#d3dbe3',
        'border-crisp': '#e2e8ee',
        'border-strong': '#c8d2dc',
        error: '#c0392b',
        'on-error': '#ffffff',
        'error-container': '#fbeceb',
        'on-error-container': '#7a1f18',
        'risk-critical': '#c0392b',
        'risk-critical-bg': '#fdf1f0',
        'risk-warning': '#b4650a',
        'risk-warning-bg': '#fbf3e4',
        'risk-success': '#0e7c66',
        'risk-success-bg': '#e8f4ef',
        navy: {
          50: '#f1f5fa',
          100: '#e2eaf4',
          200: '#c5d3e6',
          300: '#9db4d1',
          400: '#6f8fb5',
          500: '#4a6b96',
          600: '#3a5583',
          700: '#31476e',
          800: '#2a3c5c',
          900: '#22304a',
          950: '#141d2e',
        },
        govNavy: {
          DEFAULT: '#0B1220',
          dark: '#060B15',
          surface: '#111827',
          border: '#1E293B',
          accent: '#2451C4',
          hover: '#1D4099',
        },
        govEmerald: {
          DEFAULT: '#059669',
          light: '#10B981',
          dark: '#047857',
        },
        govGold: '#D97706',
        brandNavy: '#0F2C59',
        brandEmerald: '#10B981',
        brandEmeraldDark: '#059669',
        brandCoral: '#EF4444',
        brandAmber: '#F59E0B',
        brandLime: '#bef264',
        brandCream: '#FBF9F5',
        brandInk: '#111625',
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '3rem',
        'sidebar-width': '16rem',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgb(16 24 40 / 0.04)',
        '2xs': '0 0 0 1px rgb(16 24 40 / 0.03)',
        card: '0 1px 2px 0 rgb(16 24 40 / 0.04), 0 1px 3px 0 rgb(16 24 40 / 0.03)',
        lifted: '0 4px 12px -2px rgb(16 24 40 / 0.08), 0 2px 4px -2px rgb(16 24 40 / 0.04)',
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        inter: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        'headline-sm': ['1rem', { lineHeight: '1.5rem', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem' }],
        'body-sm': ['0.75rem', { lineHeight: '1rem' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.04em', fontWeight: '600' }],
        'code-xs': ['0.625rem', { lineHeight: '0.875rem', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-sm': ['0.75rem', { lineHeight: '1rem' }],
        'code-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '-0.01em' }],
        'code-lg': ['1.125rem', { lineHeight: '1.5rem', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}