/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f8fafc',
        'on-background': '#0f172a',
        'on-surface': '#0f172a',
        'surface-card': '#ffffff',
        'surface-subtle': '#f1f5f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8fafc',
        'surface-container': '#f1f5f9',
        'surface-container-high': '#e2e8f0',
        'surface-container-highest': '#cbd5e1',
        'surface-bright': '#ffffff',
        'surface-dim': '#e2e8f0',
        'surface-tint': '#0284c7',
        primary: '#0284c7',
        'on-primary': '#ffffff',
        'primary-container': '#e0f2fe',
        'on-primary-container': '#0c4a6e',
        'primary-fixed': '#e0f2fe',
        'primary-fixed-dim': '#bae6fd',
        'inverse-primary': '#38bdf8',
        'accent-cyan-deep': '#0369a1',
        secondary: '#2563eb',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2e8f0',
        'secondary-fixed': '#e2e8f0',
        'secondary-fixed-dim': '#cbd5e1',
        'on-secondary-container': '#0f172a',
        tertiary: '#059669',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d1fae5',
        'tertiary-fixed-dim': '#a7f3d0',
        'on-tertiary-container': '#064e3b',
        'text-primary': '#0f172a',
        'text-secondary': '#334155',
        'text-muted': '#64748b',
        'on-surface-variant': '#475569',
        outline: '#94a3b8',
        'outline-variant': '#cbd5e1',
        'border-crisp': '#e2e8f0',
        'border-strong': '#cbd5e1',
        error: '#dc2626',
        'on-error': '#ffffff',
        'error-container': '#fee2e2',
        'on-error-container': '#7f1d1d',
        'risk-critical': '#dc2626',
        'risk-critical-bg': '#fef2f2',
        'risk-warning': '#d97706',
        'risk-warning-bg': '#fffbeb',
        'risk-success': '#059669',
        'risk-success-bg': '#ecfdf5',
        navy: {
          50: '#eef2fb',
          100: '#d9e2f3',
          200: '#b7c7e6',
          300: '#8ba4d3',
          400: '#5f7ebd',
          500: '#4059aa',
          600: '#2f4590',
          700: '#283c78',
          800: '#233360',
          900: '#1e2b4f',
          950: '#131a30',
        },
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '3rem',
        'sidebar-width': '16rem',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        '2xs': '0 0 0 1px rgb(0 0 0 / 0.04)',
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        'headline-sm': ['1rem', { lineHeight: '1.5rem', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem' }],
        'body-sm': ['0.75rem', { lineHeight: '1rem' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-sm': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-xs': ['0.625rem', { lineHeight: '0.875rem', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-sm': ['0.75rem', { lineHeight: '1rem' }],
        'code-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '-0.01em' }],
        'code-lg': ['1.125rem', { lineHeight: '1.5rem', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}